# Generated by Django 4.1.2 on 2022-10-22 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('initialAccess', models.DateTimeField()),
                ('firstDetectTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='System_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('is_Attacker', models.BooleanField()),
                ('case', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cases.cases')),
                ('system_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cases.system_type')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('assignee', models.ForeignKey(default='User Deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cases.cases')),
                ('system', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cases.systems')),
                ('task_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cases.task_status')),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('is_AttackerCreated', models.BooleanField()),
                ('account_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cases.account_type')),
                ('case', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cases.cases')),
            ],
        ),
    ]
