# Generated by Django 4.1.2 on 2022-10-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hbi',
            name='filePath',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hbi',
            name='sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='nbi',
            name='domain',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nbi',
            name='ipAddress',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
