# Generated by Django 4.1.2 on 2022-10-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='firstDetectTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='initialAccess',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
