# Generated by Django 4.1.2 on 2022-10-24 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0002_alter_case_firstdetecttime_alter_case_initialaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='incidentManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
