# Generated by Django 4.1.2 on 2022-10-23 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0002_rename_accounts_account_rename_cases_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='incidentManager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.account_type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.case'),
        ),
        migrations.AlterField(
            model_name='case',
            name='firstDetectTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='initialAccess',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.case'),
        ),
        migrations.AlterField(
            model_name='system',
            name='system_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.system_type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case'),
        ),
        migrations.AlterField(
            model_name='task',
            name='system',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, to='cases.system'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='cases.task_status'),
        ),
    ]
