# Generated by Django 4.1.2 on 2022-10-23 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_task_status_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.system'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cases.task_status'),
        ),
    ]
